source 'https://gitcafe.com/akuandev/Specs.git'
platform :ios, '7.0'

pod 'ReactiveCocoa', '~> 2.5'
pod 'UITableView+FDTemplateLayoutCell'
pod 'MJExtension'
pod 'AFNetworking'
pod 'iConsole'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'HYBUnicodeReadable'
pod 'Masonry'
pod 'GVUserDefaults'
pod 'XXNibBridge'
pod 'BlocksKit'
pod 'SDCycleScrollView'
pod 'IQKeyboardManager'
pod 'JZNavigationExtension'
pod 'MJRefresh'
pod 'NullSafe'
pod 'Aspects'
pod 'YYCache'
pod 'VGParallaxHeader'
pod 'MMPopupView'